language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
    - yarn
branches:
  only:
    - master
script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: build
  keep-history: true
  on:
    branch: master
 